//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventStreams.Persistence {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EventStreams.Persistence.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id:    20f65c10-d7de-43b0-a527-4ccc43496bfe
        ///Time:  0001-01-01T00:00:00.0000000
        ///Type:  EventStreams.Domain.Events.BankAccount.PayeSalaryDeposited, EventStreams.Tests.Domain, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
        ///Args:  { }
        ///Hash:  pjJuhW1PkXFR1mRv/cV6+1Y/HF8=
        ///
        ///Id:    685f85da-07ac-4eb3-b7f5-f52bcd543e84
        ///Time:  0001-01-01T00:00:00.0000000
        ///Type:  EventStreams.Domain.Events.BankAccount.MadePurchase, EventStreams.Tests.Domain, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
        ///Args:  { [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FirstAndSecondEvents {
            get {
                return ResourceManager.GetString("FirstAndSecondEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id:    20f65c10-d7de-43b0-a527-4ccc43496bfe
        ///Time:  0001-01-01T00:00:00.0000000
        ///Type:  EventStreams.Domain.Events.BankAccount.PayeSalaryDeposited, EventStreams.Tests.Domain, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
        ///Args:  { }
        ///Hash:  pjJuhW1PkXFR1mRv/cV6+1Y/HF8=
        ///
        ///Id:    685f85da-07ac-4eb3-b7f5-f52bcd543e84
        ///Time:  0001-01-01T00:00:00.0000000
        ///Type:  EventStreams.Domain.Events.BankAccount.MadePurchase, EventStreams.Tests.Domain, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
        ///Args:  { [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FirstEvents {
            get {
                return ResourceManager.GetString("FirstEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hash:  YXNkYXNkYXNkYWFzZGFzZGFzZGE=
        ///
        ///Id:    20f65c10-d7de-43b0-a527-4ccc43496bfe
        ///Time:  0001-01-01T00:00:00.0000000
        ///Type:  EventStreams.Domain.Events.BankAccount.PayeSalaryDeposited, EventStreams.Tests.Domain, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
        ///Args:  { }
        ///Hash:  dWyDdzTQivXEnPpWIvVcGWtz8G4=
        ///
        ///Id:    685f85da-07ac-4eb3-b7f5-f52bcd543e84
        ///Time:  0001-01-01T00:00:00.0000000
        ///Type:  EventStreams.Domain.Events.BankAccount.MadePurchase, EventStreams.Tests.Domain, Version=0.0.0.0, Culture [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FirstEvents_WithHashSeed {
            get {
                return ResourceManager.GetString("FirstEvents_WithHashSeed", resourceCulture);
            }
        }
    }
}
